version: '3'

services:
  db:
    image: postgres
  backend:
    build: ./Backend
    command: >
      sh -c "python Backend/manage.py makemigrations &&
             python Backend/manage.py migrate &&
             python Backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./Frontend
    command: python Frontend/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code2
    ports:
      - "8001:8001"
    depends_on:
      - backend
