# Generated by Django 2.2.4 on 2019-10-09 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
